-- Wedding guestbook schema.
-- Portable MySQL: no TiDB-only data types, indexes, or functions are used.
SET time_zone = '+00:00';
--
-- status meanings:
--   pending  = waiting for review; nothing is public
--   approved = photos appear on the wedding wall
--   featured = photos appear first on the wedding wall
--   rejected = submission remains private and is not displayed
CREATE TABLE IF NOT EXISTS submissions (
  -- UUID generated by the backend, so records can be migrated without
  -- depending on a database-specific auto-increment sequence.
  id CHAR(36) NOT NULL PRIMARY KEY,

  -- Private guestbook content. `message` is returned only to the admin API.
  guest_name VARCHAR(100) NOT NULL,
  message TEXT NOT NULL,

  -- JSON array of ImgBB URLs. LONGTEXT is used instead of a native JSON type
  -- to keep exports compatible with older MySQL-compatible databases.
  photos_json LONGTEXT NOT NULL,

  -- Audit and privacy details captured when the guest submits the form.
  language_code VARCHAR(5) NOT NULL DEFAULT 'en',
  source_language_code VARCHAR(12) NOT NULL DEFAULT 'unknown',
  translations_json LONGTEXT NOT NULL,
  consent_to_publish BOOLEAN NOT NULL DEFAULT FALSE,

  -- Moderation lifecycle. The application validates the allowed values.
  status VARCHAR(16) NOT NULL DEFAULT 'pending',
  reviewed_at TIMESTAMP NULL DEFAULT NULL,
  approved_at TIMESTAMP NULL DEFAULT NULL,

  -- Creation time never changes; updated_at changes after moderation.
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  -- Supports the public wall and admin review queries.
  INDEX submissions_status_created_at (status, created_at)
);

-- One-row receiving schedule controlled by the couple. Store values in UTC.
-- NULL means "no limit": open immediately or never close.
CREATE TABLE IF NOT EXISTS guestbook_settings (
  id TINYINT NOT NULL PRIMARY KEY,
  submissions_open_at TIMESTAMP NULL DEFAULT NULL,
  submissions_close_at TIMESTAMP NULL DEFAULT NULL,
  wall_open_at TIMESTAMP NULL DEFAULT NULL,
  wall_close_at TIMESTAMP NULL DEFAULT NULL,
  auto_approve BOOLEAN NOT NULL DEFAULT FALSE,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO guestbook_settings
  (id, submissions_open_at, submissions_close_at)
VALUES
  (1, '2026-08-12 00:00:00', '2026-08-13 00:00:00')
ON DUPLICATE KEY UPDATE id = id;

-- Translation provider configuration. API keys are encrypted by the backend
-- before storage; plaintext keys are never returned to the browser.
CREATE TABLE IF NOT EXISTS translation_settings (
  id TINYINT NOT NULL PRIMARY KEY,
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  provider VARCHAR(20) NOT NULL DEFAULT 'openrouter',
  model VARCHAR(160) NOT NULL DEFAULT '',
  base_url VARCHAR(500) NOT NULL DEFAULT 'https://ollama.com',
  api_keys_encrypted LONGTEXT NOT NULL,
  key_cursor INT NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO translation_settings
  (id, enabled, provider, model, base_url, api_keys_encrypted, key_cursor)
VALUES
  (1, FALSE, 'openrouter', '', 'https://ollama.com', '', 0)
ON DUPLICATE KEY UPDATE id = id;
